// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"
)

type ShortUrl struct {
	ID        uint64
	Code      string
	Url       string
	Clicks    uint64
	CreatedAt time.Time
}
