// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store_mysql

import (
	"time"
)

type ShortUrl struct {
	ID        uint64    `json:"id"`
	Code      string    `json:"code"`
	Url       string    `json:"url"`
	Clicks    uint64    `json:"clicks"`
	CreatedAt time.Time `json:"created_at"`
}
