// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package store_mysql

import (
	"context"
	"database/sql"
)

const createShortURL = `-- name: CreateShortURL :execresult
INSERT INTO short_urls (
    code, url
) VALUES (
    ?, ?
)
`

type CreateShortURLParams struct {
	Code string `json:"code"`
	Url  string `json:"url"`
}

func (q *Queries) CreateShortURL(ctx context.Context, arg CreateShortURLParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createShortURL, arg.Code, arg.Url)
}

const deleteShortURL = `-- name: DeleteShortURL :exec
DELETE FROM short_urls
WHERE id = ?
`

func (q *Queries) DeleteShortURL(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, deleteShortURL, id)
	return err
}

const getShortURL = `-- name: GetShortURL :one
SELECT id, url FROM short_urls 
WHERE code = ? LIMIT 1
`

type GetShortURLRow struct {
	ID  uint64 `json:"id"`
	Url string `json:"url"`
}

func (q *Queries) GetShortURL(ctx context.Context, code string) (GetShortURLRow, error) {
	row := q.db.QueryRowContext(ctx, getShortURL, code)
	var i GetShortURLRow
	err := row.Scan(&i.ID, &i.Url)
	return i, err
}

const getShortURLById = `-- name: GetShortURLById :one
SELECT id, code, url FROM short_urls 
WHERE id = ? LIMIT 1
`

type GetShortURLByIdRow struct {
	ID   uint64 `json:"id"`
	Code string `json:"code"`
	Url  string `json:"url"`
}

func (q *Queries) GetShortURLById(ctx context.Context, id uint64) (GetShortURLByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getShortURLById, id)
	var i GetShortURLByIdRow
	err := row.Scan(&i.ID, &i.Code, &i.Url)
	return i, err
}

const updateShortURL = `-- name: UpdateShortURL :exec
UPDATE short_urls
SET url = ?
WHERE id = ?
`

type UpdateShortURLParams struct {
	Url string `json:"url"`
	ID  uint64 `json:"id"`
}

func (q *Queries) UpdateShortURL(ctx context.Context, arg UpdateShortURLParams) error {
	_, err := q.db.ExecContext(ctx, updateShortURL, arg.Url, arg.ID)
	return err
}
